//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvanterYonetimSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbOrder
    {
        public int orderid { get; set; }
        public System.DateTime odate { get; set; }
        public int pid { get; set; }
        public int cid { get; set; }
        public int qty { get; set; }
        public int price { get; set; }
        public int total { get; set; }
    }
}
