//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvanterYonetimSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProduct
    {
        public int pid { get; set; }
        public string pname { get; set; }
        public int pqty { get; set; }
        public int pprice { get; set; }
        public string pdescription { get; set; }
        public string pcategory { get; set; }
    }
}
